// Generated by CoffeeScript 1.6.2
var app, resources;

app = require('express')();

resources = require('./boot/resources');

resources.load(app);

app.listen(5000, function() {
  return console.log('Server started on port 5000.');
});
