// Generated by CoffeeScript 1.6.2
/*
#
#  Custom routes
#
*/

var routes;

routes = {
  '/': {
    controller: 'home'
  },
  '/about': {
    controller: 'home',
    action: 'about'
  },
  '/login': {
    controller: 'home',
    action: 'login'
  }
};

module.exports = routes;
