// Generated by CoffeeScript 1.6.2
var first_middleware, second_middleware;

first_middleware = function(req, res, next) {
  console.log("First middleware making contact.");
  return next();
};

second_middleware = function(req, res, next) {
  console.log("Second middleware received contact. Phasing to route sequence.");
  return next();
};

exports.index = function(req, res) {
  return res.send("Hello World from the Home Controller!");
};

exports.about = function(req, res) {
  return res.send("About us - we're an awesome bunch of HTML bits.");
};

exports.login = [
  first_middleware, second_middleware, function(req, res) {
    res.send('This is a login and it uses middleware. Check the console to confirm it is being called.');
    return console.log('Final Route called.');
  }
];
