// Generated by CoffeeScript 1.6.2
exports.index = function(req, res) {
  return res.send('A list of all posts.');
};

exports["new"] = function(req, res) {
  return res.send('A form to create a new post.');
};

exports.create = function(req, res) {
  return res.send('Creates a new post.');
};

exports.show = function(req, res) {
  return res.send('Show a single post.');
};

exports.edit = function(req, res) {
  return res.send('A form to edit an existing post.');
};

exports.update = function(req, res) {
  return res.send('Updates an existing post.');
};

exports.destroy = function(req, res) {
  return res.send('Deletes a post.');
};
